/**
 * @file plugins.js
 * @author andrew.rapo@jibo.com
 * @name jibo19769_jibo_channel
 * @description A channel for integrating with Jibo robots 
 *
 * Generated by the converse-cli tool for use with the Converse AI
 * Plugins SDK. https://developers.converse.ai/
 *
 * IMPORTANT: THIS FILE IS AUTO GENERATED, CHANGES MAY BE OVERRIDDEN!
 */

'use strict';
const ConversePluginsSDK = require('@converseai/plugins-sdk');
const ChannelMessages    = require('./converseai_channels');
const RegProviders       = require('./converseai_providers');

/**
 * jibo19769_jibo_channel plugin. To be used with
 * Converse AI Plugins SDK.
 *
 * @example
 * const converseai  = require('plugins.js');
 * const express     = require('express');
 * const bodyParser  = require('body-parser');
 *
 * var server = express();
 *
 * server.use(bodyParser.json());
 * server.post('/', function (req, res) {
 *    converseai.jibo19769_jibo_channel(req, res);
 * });
 *
 * @param {Object} request Express HTTP request object.
 * @param {Object} response Express HTTP response object.
 */
exports.jibo19769_jibo_channel = function (request, response) {
  var app = new ConversePluginsSDK.http({ request, response });

  if (request && request.headers && request.headers['x_converse_app_token'] && request.headers['x_converse_app_token'] === require('./app-token')) {

    app.setOnMessageInbound(ChannelMessages.onMessageInbound);
    app.setOnMessageOutbound(ChannelMessages.onMessageOutbound);

    app.setOnProviderRegister(RegProviders.onProviderRegister);
    app.setOnProviderUnregister(RegProviders.onProviderUnregister);

    app.handleRequest();
  } else {
    app._handleError(403, 'FORBIDDEN_APP_TOKEN', 'Forbidden app token set.');
  }
};
